// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImgController from "./img_controller"
application.register("img", ImgController)

import InsertStepController from "./insert_step_controller"
application.register("insert-step", InsertStepController)

import MapController from "./map_controller"
application.register("map", MapController)

import ShowController from "./show_controller"
application.register("show", ShowController)

import StepMapController from "./step_map_controller"
application.register("step-map", StepMapController)
